### ISSUE TITLE
How to Add courses and content as admin

### ISSUE THREAD

**Issue by TeslaDevX** [avuletica/eLearning#4]
How can we add content as an admin as there is no option available on localhost/admin, so that we can add the course. Also nothing appears in the courses section when we access as professor or student. Please guide me.  Thanks in advance!

**Comment by avuletica** [comment]
When you log in as an Admin user, go to admin dashboard (top-right corner), there you can see that admin does not have professor role and that is the reason he can't add any courses. 

![admin](https://user-images.githubusercontent.com/11634859/35158747-622e52a8-fd38-11e7-8a00-3993c6eb89f0.png)

If you want to add courses, log in as professor and go to his dashboard and follow steps to add a course.

![prof](https://user-images.githubusercontent.com/11634859/35158820-992c27c6-fd38-11e7-8f6e-6a9ec351437d.png)

**Comment by TeslaDevX** [comment]
I logged in as a professor and I am not still not getting any options to add a course
![elearningcapture](https://user-images.githubusercontent.com/34835762/35193467-8e5de450-fec4-11e7-983f-e43a4017640b.PNG)

**Comment by avuletica** [comment]
Click on professor (profile button) at navigation bar

![screenshot from 2018-01-21 12-15-59](https://user-images.githubusercontent.com/11634859/35193586-0e78736e-fea5-11e7-863a-f4cb7b9a74b2.png)

**Comment by TeslaDevX** [comment]
Thank you :) Also how can I assign role as a professor to a newly signed user? There is no option in Django Admin Panel

**Comment by avuletica** [comment]
Log in as Admin, go to admin dashboard (profile button), there you can see a list of users, click on one of them to edit user roles.

Edit: You can only assign roles as an admin user.

**Comment by TeslaDevX** [comment]
Got hold of it successfully. Thanks a lot :)
