### ISSUE TITLE
SMTPAuthenticationError at /accounts/register/

### ISSUE THREAD

**Issue by SoftDev18** [avuletica/eLearning#5]
Hi when I tried the registration, I couldn't do it coz I keep getting this error: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials s17-v6sm27213540pfi.165 - gsmtp')
even though I have added the settings_sensitive file in source.
thanks

ps: the user is added but is inactive

**Comment by avuletica** [comment]
Hi,

when you register a new user (if you configured email sending correctly) you should get an activation link in your email inbox, upon clicking on that link user becomes active.
